# .travis.yml 
language: c
sudo: true
install:
    - git clone git://git.drogon.net/wiringPi
    - cd wiringPi
    - git pull origin
    - ./build
    - cd ..
    - make

script:
    - dht11